# Generated by Django 4.2.11 on 2024-05-01 07:06

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('address', models.CharField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookApp.authors')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('join_date', models.DateField(default=datetime.date.today)),
                ('popularity_score', models.DecimalField(decimal_places=3, max_digits=10)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookApp.publishers')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('publshed_date', models.DateField(default=datetime.date.today)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='bookApp.authors')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookApp.publishers')),
            ],
        ),
        migrations.AddField(
            model_name='authors',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookApp.users'),
        ),
    ]
