# Generated by Django 4.2.11 on 2024-05-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0002_rename_publshed_date_books_published_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='auth',
        ),
        migrations.AddField(
            model_name='authors',
            name='auth',
            field=models.ManyToManyField(to='bookApp.authors'),
        ),
    ]
